version: '3.7'

services:
    db_softdesign: 
        image: postgres
        container_name: db_softdesign
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=softdesign
            - POSTGRES_DB=softdesign
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: backend_softdesign
        restart: always
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - db_softdesign
        depends_on: 
            - db_softdesign

volumes: 
    pgdata:
        driver: local